Repository shiX0/Medwell, pull requests merged in 2023-07, with the labels that each got.

#40 added testing part
  lib/Screens/AddMedsPage.dart
  lib/Screens/EditMedsPage.dart
  lib/repositories/MedsRepository.dart
  pubspec.lock
  pubspec.yaml
  test/unittesting/Meds_Testing.dart
  test/unittesting/unit_test.dart
Labels: enhancement, functionality

#42 Done Testing and viewmodel✅
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/icons/app_logo.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/Screens/DetailsPage.dart
  lib/Screens/ProfilePage.dart
  lib/main.dart
  lib/models/UserModel.dart
  lib/repositories/AuthRepository.dart
  lib/repositories/UserRepository.dart
  lib/viewmodels/Profile_viewmodel.dart
  pubspec.lock
  pubspec.yaml
  test/unittesting/User_Testing.dart
Labels: enhancement, functionality

#43 Added notifications scheduled and it works. Also testing and other minor changes
  lib/Components/DropDown.dart
  lib/Screens/AddMedsPage.dart
  lib/Screens/EditMedsPage.dart
  lib/Screens/NavigationPage.dart
  lib/models/MedsModel.dart
  lib/services/NotificationService.dart
  lib/wigets/InputTestDemo.dart
  lib/wigets/MakePriceTest.dart
  lib/wigets/widget_testing/Widget_test_demo.dart
Labels: bug, enhancement, help wanted, functionality

#45 Added various features , exception handling, fab button and keyboard renderoverflow fixed.
  lib/Screens/AddMedsPage.dart
  lib/Screens/LandingPage.dart
  lib/Screens/NavPages.dart
  lib/models/MedsModel.dart
Labels: bug, enhancement, functionality

#49 Added id for meds in front
  lib/Screens/AddMedsPage.dart
Labels: enhancement, functionality

#52 Done new auth view model
  lib/Components/ProfileButton.dart
  lib/Screens/DetailsPage.dart
  lib/Screens/LoginPage.dart
  lib/Screens/ProfilePage.dart
  lib/main.dart
  lib/models/UserModel.dart
  lib/repositories/AuthRepository.dart
  lib/repositories/UserRepository.dart
  lib/viewmodels/Auth_viewmodel.dart
  lib/viewmodels/Profile_viewmodel.dart
  pubspec.lock
  test/unittesting/User_Testing.dart
Labels: enhancement

#53 Updated viewmodel & repo functions
  lib/Screens/MedsOnClickPage.dart
  lib/Screens/NavPages.dart
  lib/models/MedsModel.dart
  lib/repositories/MedsRepository.dart
  lib/viewmodels/Meds_viewmodel.dart
Labels: enhancement, functionality

#57 done period part
  lib/Screens/LoginPage.dart
  lib/Screens/PeriodDetailsPage.dart
  lib/Screens/PeriodTrackerPage.dart
  lib/Screens/ProfilePage.dart
  lib/main.dart
  lib/models/PeriodModel.dart
  lib/repositories/PeriodRepository.dart
  lib/viewmodels/Period_viewmodel.dart
Labels: enhancement

#58 Edit page done, delete also works, need minor change for notification name in addmeds, and dropdown prefill not working in editmeds
  lib/Components/DropDown.dart
  lib/Screens/AddMedsPage.dart
  lib/Screens/EditMedsPage.dart
  lib/Screens/MedsOnClickPage.dart
  lib/Screens/NavPages.dart
  lib/main.dart
  lib/models/MedsModel.dart
  lib/repositories/MedsRepository.dart
  lib/viewmodels/Meds_viewmodel.dart
Labels: enhancement, functionality

#59 Updated homepage semifinal
  assets/icons/Group 2.png
  lib/Components/Square.dart
  lib/Screens/CalenderPage.dart
  lib/Screens/HomePage.dart
  lib/main.dart
Labels: enhancement, question, functionality
